### ISSUE TITLE
Add simple authentication system based on RBAC

### ISSUE THREAD

**Issue by dkraczkowski** [kodemore/chocs#71]
Each endpoint may define `x-auth` property which will contain value of `scope`(s) that are required in order to access the endpoint. Additionally every schema in the component can additionally implement `x-auth:*` property to limit access to certain fields.

Example:
```
/pets/{id}:
    get:
      description:
         ...
      x-auth: pet:read
```

```
NewPet:
      type: object
      required:
        - name
      properties:
        name:
          type: string
        tag:
          type: string
          x-auth:read: pet:read
          x-auth:update: pet:manage
```
